/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectKalkulator;

/**
 *
 * @author yasmin
 */
public class designLingkaran extends javax.swing.JFrame {

    /**
     * Creates new form designPersegi
     */
    public designLingkaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sifatLingkaran = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kalkulatorLingkaran = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kembaliLingkaran = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        sifat = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kalkulator = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jarijari = new javax.swing.JTextField();
        hitung3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        luasLingkaran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        kelilingLingkaran = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        cbLuas = new javax.swing.JComboBox<>();
        cbKeliling = new javax.swing.JComboBox<>();
        textDiameter = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        sifatLingkaran.setBackground(new java.awt.Color(153, 153, 255));
        sifatLingkaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifatLingkaranMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIFAT & RUMUS");

        javax.swing.GroupLayout sifatLingkaranLayout = new javax.swing.GroupLayout(sifatLingkaran);
        sifatLingkaran.setLayout(sifatLingkaranLayout);
        sifatLingkaranLayout.setHorizontalGroup(
            sifatLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatLingkaranLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sifatLingkaranLayout.setVerticalGroup(
            sifatLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifatLingkaranLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        kalkulatorLingkaran.setBackground(new java.awt.Color(153, 153, 255));
        kalkulatorLingkaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kalkulatorLingkaranMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KALKULATOR");

        javax.swing.GroupLayout kalkulatorLingkaranLayout = new javax.swing.GroupLayout(kalkulatorLingkaran);
        kalkulatorLingkaran.setLayout(kalkulatorLingkaranLayout);
        kalkulatorLingkaranLayout.setHorizontalGroup(
            kalkulatorLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorLingkaranLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kalkulatorLingkaranLayout.setVerticalGroup(
            kalkulatorLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorLingkaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        kembaliLingkaran.setBackground(new java.awt.Color(153, 153, 255));
        kembaliLingkaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliLingkaranMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KEMBALI");

        javax.swing.GroupLayout kembaliLingkaranLayout = new javax.swing.GroupLayout(kembaliLingkaran);
        kembaliLingkaran.setLayout(kembaliLingkaranLayout);
        kembaliLingkaranLayout.setHorizontalGroup(
            kembaliLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliLingkaranLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kembaliLingkaranLayout.setVerticalGroup(
            kembaliLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliLingkaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifatLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kalkulatorLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembaliLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(sifatLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalkulatorLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembaliLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        sifat.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\yasmin\\icons8-circle-100.png")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setText("1. Semua titik pada lingkaran berjarak sama dari titik ");

        jLabel8.setText("2. Diameter adalah dua kali panjang jari-jari ( d=2×r). ");

        jLabel9.setText("3. Keliling:  K=2×π×r. ");

        jLabel10.setText("4. Luas:  L=π×r  2  .");

        jLabel11.setText("pusat (disebut jari-jari,   r). ");

        javax.swing.GroupLayout sifatLayout = new javax.swing.GroupLayout(sifat);
        sifat.setLayout(sifatLayout);
        sifatLayout.setHorizontalGroup(
            sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatLayout.createSequentialGroup()
                .addGroup(sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sifatLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sifatLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        sifatLayout.setVerticalGroup(
            sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", sifat);

        kalkulator.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yasmin\\icons8-circle-100.png")); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel1.setText("Jari-Jari");

        hitung3.setText("Hitung");
        hitung3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Luas");

        luasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasLingkaranActionPerformed(evt);
            }
        });

        jLabel13.setText("Keliling");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        cbLuas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm²", "mm²", "dm²", "m²" }));

        cbKeliling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "mm", "dm", "m" }));
        cbKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelilingActionPerformed(evt);
            }
        });

        textDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiameterActionPerformed(evt);
            }
        });

        jLabel14.setText("Diameter");

        javax.swing.GroupLayout kalkulatorLayout = new javax.swing.GroupLayout(kalkulator);
        kalkulator.setLayout(kalkulatorLayout);
        kalkulatorLayout.setHorizontalGroup(
            kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                        .addComponent(reset)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                        .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kalkulatorLayout.createSequentialGroup()
                                .addComponent(jarijari, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hitung3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kalkulatorLayout.createSequentialGroup()
                                .addComponent(luasLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                                    .addComponent(kelilingLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(cbKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))))
        );
        kalkulatorLayout.setVerticalGroup(
            kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jarijari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelilingLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("tab3", kalkulator);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 390, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sifatLingkaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifatLingkaranMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_sifatLingkaranMouseClicked

    private void kalkulatorLingkaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kalkulatorLingkaranMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_kalkulatorLingkaranMouseClicked

    private void kembaliLingkaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliLingkaranMouseClicked
        Kalkulator kalkulator = new Kalkulator ();
        kalkulator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliLingkaranMouseClicked

    private void hitung3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung3ActionPerformed
        Lingkaran l = new Lingkaran();
        String optionLuas = cbLuas.getSelectedItem().toString();
        String optionKeliling = cbKeliling.getSelectedItem().toString();
        double r = Double.parseDouble(jarijari.getText());
        double d = l.setDiameter(r);
        double luas = l.setLuas(r);
        double keliling = l.setKeliling(r);

        switch (optionLuas){
            case "cm²":
            luas = l.setLuas(r);
            break;
            case "mm²":
            luas = l.setLuas(r)*100;
            break;
            case "dm²":
            luas = l.setLuas(r)/100;
            break;
            case "m²":
            luas = l.setLuas(r)/10000;
            break;
        }
        switch (optionKeliling){
            case "cm":
            keliling = l.setKeliling(r);
            break;
            case "mm":
            keliling = l.setKeliling(r)*10;
            break;
            case "dm":
            keliling = l.setKeliling(r)/10;
            break;
            case "m":
            keliling = l.setKeliling(r)/100;
            break;
        }
        textDiameter.setText(new String().valueOf(d));
        luasLingkaran.setText(new String().valueOf(luas));
        kelilingLingkaran.setText(new String().valueOf(keliling));
    }//GEN-LAST:event_hitung3ActionPerformed

    private void luasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasLingkaranActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        jarijari.setText(null);
        textDiameter.setText(null);
        luasLingkaran.setText(null);
        kelilingLingkaran.setText(null);
        cbLuas.setSelectedIndex(0);
        cbKeliling.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    private void cbKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKelilingActionPerformed

    private void textDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiameterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(designLingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(designLingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(designLingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(designLingkaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new designLingkaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbKeliling;
    private javax.swing.JComboBox<String> cbLuas;
    private javax.swing.JButton hitung3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jarijari;
    private javax.swing.JPanel kalkulator;
    private javax.swing.JPanel kalkulatorLingkaran;
    private javax.swing.JTextField kelilingLingkaran;
    private javax.swing.JPanel kembaliLingkaran;
    private javax.swing.JTextField luasLingkaran;
    private javax.swing.JButton reset;
    private javax.swing.JPanel sifat;
    private javax.swing.JPanel sifatLingkaran;
    private javax.swing.JTextField textDiameter;
    // End of variables declaration//GEN-END:variables
}
