/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectKalkulator;

/**
 *
 * @author yasmin
 */
public class designSegitigaSikuSiku extends javax.swing.JFrame {

    /**
     * Creates new form designPersegi
     */
    public designSegitigaSikuSiku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sifatSegitigaSiku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kalkulatorSegitigaSiku = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kembaliSegitigaSiku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        sifat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kalkulator = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panjang = new javax.swing.JLabel();
        sisiA = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        luasSegitigaSiku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kelilingSegitigaSiku = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        cbLuas = new javax.swing.JComboBox<>();
        cbKeliling = new javax.swing.JComboBox<>();
        lebar = new javax.swing.JLabel();
        sisiB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sisiC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        sifatSegitigaSiku.setBackground(new java.awt.Color(153, 153, 255));
        sifatSegitigaSiku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifatSegitigaSikuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIFAT & RUMUS");

        javax.swing.GroupLayout sifatSegitigaSikuLayout = new javax.swing.GroupLayout(sifatSegitigaSiku);
        sifatSegitigaSiku.setLayout(sifatSegitigaSikuLayout);
        sifatSegitigaSikuLayout.setHorizontalGroup(
            sifatSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifatSegitigaSikuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
        sifatSegitigaSikuLayout.setVerticalGroup(
            sifatSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatSegitigaSikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kalkulatorSegitigaSiku.setBackground(new java.awt.Color(153, 153, 255));
        kalkulatorSegitigaSiku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kalkulatorSegitigaSikuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KALKULATOR");

        javax.swing.GroupLayout kalkulatorSegitigaSikuLayout = new javax.swing.GroupLayout(kalkulatorSegitigaSiku);
        kalkulatorSegitigaSiku.setLayout(kalkulatorSegitigaSikuLayout);
        kalkulatorSegitigaSikuLayout.setHorizontalGroup(
            kalkulatorSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorSegitigaSikuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
        );
        kalkulatorSegitigaSikuLayout.setVerticalGroup(
            kalkulatorSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorSegitigaSikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        kembaliSegitigaSiku.setBackground(new java.awt.Color(153, 153, 255));
        kembaliSegitigaSiku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliSegitigaSikuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KEMBALI");

        javax.swing.GroupLayout kembaliSegitigaSikuLayout = new javax.swing.GroupLayout(kembaliSegitigaSiku);
        kembaliSegitigaSiku.setLayout(kembaliSegitigaSikuLayout);
        kembaliSegitigaSikuLayout.setHorizontalGroup(
            kembaliSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliSegitigaSikuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        kembaliSegitigaSikuLayout.setVerticalGroup(
            kembaliSegitigaSikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliSegitigaSikuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifatSegitigaSiku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kembaliSegitigaSiku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kalkulatorSegitigaSiku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(sifatSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kalkulatorSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembaliSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        sifat.setBackground(new java.awt.Color(153, 255, 204));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\yasmin\\icons8-trigonometry-100.png")); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel1.setText("1. Salah satu sudutnya adalah 90 derajat. ");

        jLabel10.setText("2. Sisi di depan sudut siku-siku disebut hipotenusa,");

        jLabel11.setText("  yang merupakan sisi terpanjang.");

        jLabel12.setText("3. Teorema Pythagoras berlaku:  a² + b² = c²  ");

        jLabel13.setText("4. Luas:  𝐿 = (𝑎 × 𝑏)/2");

        jLabel14.setText("5. Keliling:  𝐾 = 𝑎 + 𝑏 + 𝑐 ");

        javax.swing.GroupLayout sifatLayout = new javax.swing.GroupLayout(sifat);
        sifat.setLayout(sifatLayout);
        sifatLayout.setHorizontalGroup(
            sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatLayout.createSequentialGroup()
                .addGroup(sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sifatLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sifatLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addGroup(sifatLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        sifatLayout.setVerticalGroup(
            sifatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifatLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", sifat);

        kalkulator.setBackground(new java.awt.Color(153, 255, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yasmin\\icons8-trigonometry-100.png")); // NOI18N
        jLabel5.setText("jLabel5");

        panjang.setText("Sisi A / Tinggi");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel6.setText("Luas");

        jLabel7.setText("Keliling");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        cbLuas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm²", "mm²", "dm²", "m²" }));

        cbKeliling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "mm", "dm", "m" }));

        lebar.setText("Sisi B / Alas");

        jLabel8.setText("Sisi C ");

        javax.swing.GroupLayout kalkulatorLayout = new javax.swing.GroupLayout(kalkulator);
        kalkulator.setLayout(kalkulatorLayout);
        kalkulatorLayout.setHorizontalGroup(
            kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset)
                .addGap(62, 62, 62))
            .addGroup(kalkulatorLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kalkulatorLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalkulatorLayout.createSequentialGroup()
                        .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kalkulatorLayout.createSequentialGroup()
                                .addComponent(sisiC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hitung))
                            .addGroup(kalkulatorLayout.createSequentialGroup()
                                .addComponent(luasSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kalkulatorLayout.createSequentialGroup()
                                .addComponent(kelilingSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kalkulatorLayout.createSequentialGroup()
                                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sisiA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panjang)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kalkulatorLayout.createSequentialGroup()
                                        .addComponent(lebar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 39, Short.MAX_VALUE))
                                    .addComponent(sisiB))))
                        .addGap(88, 88, 88))))
            .addGroup(kalkulatorLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kalkulatorLayout.setVerticalGroup(
            kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulatorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panjang)
                    .addComponent(lebar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sisiB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisiC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelilingSegitigaSiku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reset)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("tab3", kalkulator);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 390, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sifatSegitigaSikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifatSegitigaSikuMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_sifatSegitigaSikuMouseClicked

    private void kalkulatorSegitigaSikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kalkulatorSegitigaSikuMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_kalkulatorSegitigaSikuMouseClicked

    private void kembaliSegitigaSikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliSegitigaSikuMouseClicked
        Kalkulator kalkulator = new Kalkulator ();
        kalkulator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliSegitigaSikuMouseClicked

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        SegitigaSiku ss = new SegitigaSiku();
        String optionLuas = cbLuas.getSelectedItem().toString();
        String optionKeliling = cbKeliling.getSelectedItem().toString();
        double a = Double.parseDouble(sisiA.getText());
        double b = Double.parseDouble(sisiB.getText());
        double c = ss.setSisiMiring(a, b);
        double luas = ss.setLuas(a, b);
        double keliling = ss.setKeliling(a, b, c);

        switch (optionLuas){
            case "cm²":
            luas = ss.setLuas(a,b);
            break;
            case "mm²":
            luas = ss.setLuas(a,b)*100;
            break;
            case "dm²":
            luas = ss.setLuas(a,b)/100;
            break;
            case "m²":
            luas = ss.setLuas(a,b)/10000;
            break;
        }
        switch (optionKeliling){
            case "cm":
            keliling = ss.setKeliling(a,b,c);
            break;
            case "mm":
            keliling = ss.setKeliling(a,b,c)*10;
            break;
            case "dm":
            keliling = ss.setKeliling(a,b,c)/10;
            break;
            case "m":
            keliling = ss.setKeliling(a,b,c)/100;
            break;
        }
        sisiC.setText(new String(). valueOf(c));
        luasSegitigaSiku.setText(new String().valueOf(luas));
        kelilingSegitigaSiku.setText(new String().valueOf(keliling));
    }//GEN-LAST:event_hitungActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        sisiA.setText(null);
        sisiB.setText(null);
        sisiC.setText(null);
        luasSegitigaSiku.setText(null);
        kelilingSegitigaSiku.setText(null);
        cbLuas.setSelectedIndex(0);
        cbKeliling.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(designSegitigaSikuSiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(designSegitigaSikuSiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(designSegitigaSikuSiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(designSegitigaSikuSiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new designSegitigaSikuSiku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbKeliling;
    private javax.swing.JComboBox<String> cbLuas;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel kalkulator;
    private javax.swing.JPanel kalkulatorSegitigaSiku;
    private javax.swing.JTextField kelilingSegitigaSiku;
    private javax.swing.JPanel kembaliSegitigaSiku;
    private javax.swing.JLabel lebar;
    private javax.swing.JTextField luasSegitigaSiku;
    private javax.swing.JLabel panjang;
    private javax.swing.JButton reset;
    private javax.swing.JPanel sifat;
    private javax.swing.JPanel sifatSegitigaSiku;
    private javax.swing.JTextField sisiA;
    private javax.swing.JTextField sisiB;
    private javax.swing.JTextField sisiC;
    // End of variables declaration//GEN-END:variables
}
